export const BestSellingCoursesData: object[] = [
	{
		id: 1,
		title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
		category: "design",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/machine-learning.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 2,
		title: "The Complete 2021 Web Development Bootcamp",
		category: "developments",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/web-dev-bootcamp.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 3,
		title: "Learn Python Programming Masterclass",
		category: "business",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/learn-python.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 4,
		title: "The Complete Digital Marketing Course - 12 Courses in 1",
		category: "marketing",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/digital-marketing.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 5,
		title: "Reiki Level I, II and Master/Teacher Program",
		category: "it & software",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/reiki-level.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 6,
		title: "The Complete Foundation Stock Trading Course",
		category: "music",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/stock-trading.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 7,
		title: "Beginner to Pro in Excel: Financial Modeling and Valuati...",
		category: "marketing",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/pro-in-excel.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 8,
		title: "The Python Mega Course: Build 10 Real World Applications",
		category: "health & fitness",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/python-mega-course.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 9,
		title: "Copywriting - Become a Freelance Copywriter, your ow...",
		category: "design",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/copywriting.png",
		review: 5,
		registeredStudents: 265756,
	},
	{
		id: 10,
		title: "Google Analytics Certification - Learn How To Pass The Exam",
		category: "lifestyle",
		price: 57,
		thumbnail: "../../../assets/BestSellingCourses/google-analytics.png",
		review: 5,
		registeredStudents: 265756,
	},
];
