import { devCourseDataType } from "@/types/devCourseData";
export const devCourseData: devCourseDataType[] = [
  {
    id: 482193,
    title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
    category: "design",
    categoryColor: "#993D20",
    categoryBgColor: "#FFEEE8",
    price: 57,
    thumbnail: "/Courses/machine-learning.png",
    review: 5.0,
    registeredStudents: 212546,
    courseOwner: "kevin gilbert",
    level: "beginner",
    duration: 6,
    description: `"Machine Learning A-Z™: Hands-On Python & R In" is a comprehensive course designed to take you from a beginner to a proficient machine learning practitioner. This course covers a wide range of topics in machine learning, from basic concepts to advanced technologyniques, using Python and R, two of the most popular programming languages in data science.`,
  },
  {
    id: 917504,
    title: "The Complete 2021 Web Development Bootcamp",
    category: "developments",
    categoryColor: "#342F98",
    categoryBgColor: "#EBEBFF",
    price: 64,
    thumbnail: "/Courses/web-dev-bootcamp.png",
    review: 4.6,
    registeredStudents: 65423,
    courseOwner: "angela yu",
    level: "beginner",
    duration: 12,
    description: `Master web development in 2021 with "The Complete 2021 Web Development Bootcamp." Led by expert instructor Angela Yu, this course takes you from zero to hero, covering HTML, CSS, JavaScript, Node.js, and more. Whether you want to build websites, start a career in technology, or create your own web applications, this comprehensive bootcamp equips you with all the necessary skills.`,
  },
  {
    id: 356781,
    title: "Learn Python Programming Masterclass",
    category: "business",
    categoryColor: "#15711F",
    categoryBgColor: "#E1F7E3",
    price: 49,
    thumbnail: "/Courses/learn-python.png",
    review: 4.8,
    registeredStudents: 1246,
    courseOwner: "tim buchalka",
    level: "intermediate",
    duration: 8,
    description: `Dive deep into Python with the "Learn Python Programming Masterclass." This course is ideal for those with some coding experience who want to enhance their Python skills. Instructor Tim Buchalka guides you through real-world examples and projects, covering everything from basic syntax to advanced concepts, including object-oriented programming and web development.`,
  },
  {
    id: 628294,
    title: "The Complete Digital Marketing Course - 12 Courses in 1",
    category: "marketing",
    categoryColor: "#342F98",
    categoryBgColor: "#EBEBFF",
    price: 39,
    thumbnail: "/Courses/digital-marketing.png",
    review: 4.7,
    registeredStudents: 9875,
    courseOwner: "robie gallagher",
    level: "advanced",
    duration: 20,
    description: `"The Complete Digital Marketing Course - 12 Courses in 1" is your ultimate guide to mastering digital marketing. Covering everything from SEO, Google Ads, and social media marketing to email marketing and content creation, this course provides all the tools you need to excel in the digital world. Perfect for marketers, entrepreneurs, and business owners.`,
  },
  {
    id: 735182,
    title: "Reiki Level I, II and Master/Teacher Program",
    category: "it & software",
    categoryColor: "#993D20",
    categoryBgColor: "#FFEEE8",
    price: 49,
    thumbnail: "/Courses/reiki-level.png",
    review: 4.9,
    registeredStudents: 34965,
    courseOwner: "lisa powers",
    level: "beginner",
    duration: 5,
    description: `Unlock the healing power of Reiki with the "Reiki Level I, II and Master/Teacher Program." Taught by Reiki Master Lisa Powers, this course is designed for anyone looking to learn the art of Reiki healing. You'll gain the knowledge and skills to perform Reiki on yourself and others, eventually mastering the technologyniques to teach and guide others.`,
  },
];
