import { Feedback } from "@/types/feedback";

export const feedbackDatabase: Feedback[] = [
  {
    id: 1,
    name: "Emily Johnson",
    profileImage: "../../ProfilePhoto/eleanor.svg",
    comment: "Absolutely loved this course! The instructor was knowledgeable and made complex topics easy to understand. Highly recommend!",
    rating: 5,
    date: "2024-08-01T10:30:00Z",
},
{
    id: 2,
    name: "Michael Thompson",
    profileImage: "../../ProfilePhoto/man.svg",
    comment: "Great content overall, but I felt some sections could have been more detailed. Still, a very solid course.",
    rating: 4,
    date: "2024-08-02T14:45:00Z",
},
{
    id: 3,
    name: "Sarah Williams",
    profileImage: "../../ProfilePhoto/woman.svg",
    comment: "The course was okay, but I think it could be improved with more interactive elements. The material is good, but the delivery felt a bit dry.",
    rating: 3,
    date: "2024-08-03T09:20:00Z",
},
{
    id: 4,
    name: "James Brown",
    profileImage: "../../ProfilePhoto/Guy.svg",
    comment: "I was disappointed with the course. The content was not as in-depth as I expected, and the examples were outdated.",
    rating: 2,
    date: "2024-08-04T11:15:00Z",
},
{
    id: 5,
    name: "Olivia Davis",
    profileImage: "../../ProfilePhoto/Bessie.svg",
    comment: "Very informative and well-structured. The pacing was just right, though I wish there were more real-world case studies included.",
    rating: 4,
    date: "2024-08-05T16:30:00Z",
},
{
    id: 6,
    name: "Christopher Wilson",
    profileImage: "../../ProfilePhoto/Dianne.svg",
    comment: "This course exceeded my expectations! The hands-on projects were especially helpful. I feel much more confident in my skills now.",
    rating: 5,
    date: "2024-08-06T13:00:00Z",
},
{
    id: 7,
    name: "Sophia Martinez",
    profileImage: "../../ProfilePhoto/eleanor.svg",
    comment: "Decent course, but it didn't really stand out. Some parts were great, but others felt a bit too basic for my level.",
    rating: 3,
    date: "2024-08-07T12:45:00Z",
},
{
    id: 8,
    name: "Daniel Clark",
    profileImage: "../../ProfilePhoto/Bessie.svg",
    comment: "Fantastic course! The instructor was engaging, and the content was both challenging and rewarding. I learned a lot!",
    rating: 5,
    date: "2024-08-08T14:00:00Z",
},
{
    id: 9,
    name: "Isabella Rodriguez",
    profileImage: "../../ProfilePhoto/woman.svg",
    comment: "I enjoyed this course and learned a lot. The assignments were practical and reinforced the concepts well. Could have used more examples, though.",
    rating: 4,
    date: "2024-08-09T10:00:00Z",
},
{
    id: 10,
    name: "David Lewis",
    profileImage: "../../ProfilePhoto/Guy.svg",
    comment: "I struggled with the course. The content was not well organized, and I found the instructions unclear at times. It needs more polish.",
    rating: 2,
    date: "2024-08-10T09:30:00Z",
},
{
  id: 11,
  name: "Emma Harris",
  profileImage: "../../ProfilePhoto/eleanor.svg",
  comment: "This course was a great introduction to the topic. I especially liked the practical examples. Well done!",
  rating: 4,
  date: "2024-08-11T11:30:00Z",
},
{
  id: 12,
  name: "William Moore",
  profileImage: "../../ProfilePhoto/man.svg",
  comment: "Good course, but it could have been better with more advanced content. Suitable for beginners.",
  rating: 3,
  date: "2024-08-12T14:20:00Z",
},
{
  id: 13,
  name: "Mia Walker",
  profileImage: "../../ProfilePhoto/woman.svg",
  comment: "I absolutely loved the hands-on approach of this course. It helped solidify my understanding of the material.",
  rating: 5,
  date: "2024-08-13T13:15:00Z",
},
{
  id: 14,
  name: "Henry White",
  profileImage: "../../ProfilePhoto/Guy.svg",
  comment: "The course was informative but could use more up-to-date examples. Some of the content felt outdated.",
  rating: 3,
  date: "2024-08-14T10:40:00Z",
},
{
  id: 15,
  name: "Amelia Young",
  profileImage: "../../ProfilePhoto/Bessie.svg",
  comment: "Very engaging course with a lot of practical information. I would definitely recommend it to others.",
  rating: 4,
  date: "2024-08-15T15:45:00Z",
},
{
  id: 16,
  name: "Liam King",
  profileImage: "../../ProfilePhoto/eleanor.svg",
  comment: "Excellent course! The instructor was very clear and provided great examples. I feel well-prepared to apply what I learned.",
  rating: 5,
  date: "2024-08-16T12:00:00Z",
},
{
  id: 17,
  name: "Evelyn Scott",
  profileImage: "../../ProfilePhoto/Dianne.svg",
  comment: "The course was decent, but I expected more depth. It’s a good starting point, but advanced learners might find it lacking.",
  rating: 3,
  date: "2024-08-17T09:10:00Z",
},
{
  id: 18,
  name: "Alexander Green",
  profileImage: "../../ProfilePhoto/Bessie.svg",
  comment: "Great course overall! The instructor was knowledgeable, and the content was very relevant. I learned a lot.",
  rating: 4,
  date: "2024-08-18T13:50:00Z",
},
{
  id: 19,
  name: "Sophia Hill",
  profileImage: "../../ProfilePhoto/woman.svg",
  comment: "I enjoyed this course but felt that some of the topics were covered too briefly. More depth would have been nice.",
  rating: 4,
  date: "2024-08-19T11:30:00Z",
},
{
  id: 20,
  name: "Lucas Baker",
  profileImage: "../../ProfilePhoto/Guy.svg",
  comment: "I had a hard time following the course. The material was not well structured, and I found it difficult to stay engaged.",
  rating: 2,
  date: "2024-08-20T10:00:00Z",
},
{
  id: 21,
  name: "Grace Adams",
  profileImage: "../../ProfilePhoto/eleanor.svg",
  comment: "This course was very helpful and provided a lot of valuable information. The instructor was great!",
  rating: 5,
  date: "2024-08-21T15:00:00Z",
},
{
  id: 22,
  name: "Mason Gonzalez",
  profileImage: "../../ProfilePhoto/man.svg",
  comment: "The course was good, but I felt that some sections were too basic. It’s a solid course for beginners.",
  rating: 3,
  date: "2024-08-22T14:30:00Z",
},
{
  id: 23,
  name: "Isabella Carter",
  profileImage: "../../ProfilePhoto/woman.svg",
  comment: "An excellent course! The projects were very useful in helping me understand the material. Highly recommended.",
  rating: 5,
  date: "2024-08-23T11:45:00Z",
},
{
  id: 24,
  name: "Ethan Perez",
  profileImage: "../../ProfilePhoto/Guy.svg",
  comment: "I was a bit disappointed with this course. The content didn’t go as deep as I expected, and I found it lacking in detail.",
  rating: 2,
  date: "2024-08-24T12:20:00Z",
},
{
  id: 25,
  name: "Ava Ramirez",
  profileImage: "../../ProfilePhoto/Bessie.svg",
  comment: "Great course overall, but I wish there was more focus on advanced topics. Still, I learned a lot!",
  rating: 4,
  date: "2024-08-25T16:10:00Z",
},

];

export default feedbackDatabase;
