import { BestSellingCoursesType } from "@/types/BestSellingCourses";

export const BestSellingCoursesData: BestSellingCoursesType[] = [
  {
    title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
    category: "design",
    categoryColor: "#993D20",
    categoryBgColor: "#FFEEE8",
    price: 57,
    thumbnail: "/BestSellingCourses/machine-learning.png",
    review: 5.0,
    registeredStudents: 212546,
  },
  {
    title: "The Complete 2021 Web Development Bootcamp",
    category: "developments",
    categoryColor: "#342F98",
    categoryBgColor: "#EBEBFF",
    price: 64,
    thumbnail: "/BestSellingCourses/web-dev-bootcamp.png",
    review: 4.6,
    registeredStudents: 65423,
  },
  {
    title: "Learn Python Programming Masterclass",
    category: "business",
    categoryColor: "#15711F",
    categoryBgColor: "#E1F7E3",
    price: 49,
    thumbnail: "/BestSellingCourses/learn-python.png",
    review: 4.8,
    registeredStudents: 1246,
  },
  {
    title: "The Complete Digital Marketing Course - 12 Courses in 1",
    category: "marketing",
    categoryColor: "#342F98",
    categoryBgColor: "#EBEBFF",
    price: 39,
    thumbnail: "/BestSellingCourses/digital-marketing.png",
    review: 4.7,
    registeredStudents: 9875,
  },
  {
    title: "Reiki Level I, II and Master/Teacher Program",
    category: "it & software",
    categoryColor: "#993D20",
    categoryBgColor: "#FFEEE8",
    price: 49,
    thumbnail: "/BestSellingCourses/reiki-level.png",
    review: 4.9,
    registeredStudents: 34965,
  },
  {
    title: "The Complete Foundation Stock Trading Course",
    category: "music",
    categoryColor: "#993D20",
    categoryBgColor: "#FFEEE8",
    price: 99,
    thumbnail: "/BestSellingCourses/stock-trading.png",
    review: 4.1,
    registeredStudents: 719433,
  },
  {
    title: "Beginner to Pro in Excel: Financial Modeling and Valuati...",
    category: "marketing",
    categoryColor: "#342F98",
    categoryBgColor: "#EBEBFF",
    price: 43,
    thumbnail: "/BestSellingCourses/pro-in-excel.png",
    review: 5,
    registeredStudents: 93213,
  },
  {
    title: "The Python Mega Course: Build 10 Real World Applications",
    category: "health & fitness",
    categoryColor: "#15711F",
    categoryBgColor: "#E1F7E3",
    price: 19,
    thumbnail: "/BestSellingCourses/python-mega-course.png",
    review: 5.0,
    registeredStudents: 651395,
  },
  {
    title: "Copywriting - Become a Freelance Copywriter, your ow...",
    category: "design",
    categoryColor: "#993D20",
    categoryBgColor: "#FFEEE8",
    price: 48,
    thumbnail: "/BestSellingCourses/copywriting.png",
    review: 3.9,
    registeredStudents: 424657,
  },
  {
    title: "Google Analytics Certification - Learn How To Pass The Exam",
    category: "lifestyle",
    categoryColor: "#65390C",
    categoryBgColor: "#FFF2E5",
    price: 69,
    thumbnail: "/BestSellingCourses/google-analytics.png",
    review: 4.4,
    registeredStudents: 316474,
  },
];
