import { CourseFilterData } from "@/types/courseFilter";

export const categories: CourseFilterData[] = [
  {
    category: "development",
    icon: "/CourseListFilter/cpu.svg",
    subCategories: [
      { name: "web development", courseNumber: 574, isSub: true },
      { name: "data science", courseNumber: 568, isSub: true },
      { name: "mobile development", courseNumber: 1345, isSub: true },
      { name: "software testing", courseNumber: 317, isSub: true },
      { name: "software engineering", courseNumber: 31, isSub: true },
      { name: "software development tools", courseNumber: 558, isSub: true },
      { name: "no-code development", courseNumber: 37, isSub: true },
    ],
  },
  {
    category: "business",
    icon: "/CourseListFilter/hand-shake.svg",
    subCategories: [
      { name: "entrepreneurship", courseNumber: 150, isSub: true },
      { name: "business strategy", courseNumber: 432, isSub: true },
      { name: "project management", courseNumber: 298, isSub: true },
      { name: "business law", courseNumber: 89, isSub: true },
      { name: "business analytics", courseNumber: 223, isSub: true },
      { name: "sales", courseNumber: 314, isSub: true },
      { name: "business communication", courseNumber: 187, isSub: true },
    ],
  },
  {
    category: "finance and accounting",
    icon: "/CourseListFilter/credit-card.svg",
    subCategories: [
      { name: "financial analysis", courseNumber: 210, isSub: true },
      { name: "accounting", courseNumber: 324, isSub: true },
      { name: "investing", courseNumber: 489, isSub: true },
      { name: "personal finance", courseNumber: 530, isSub: true },
      { name: "taxes", courseNumber: 149, isSub: true },
      { name: "financial modeling", courseNumber: 275, isSub: true },
      { name: "cryptocurrency", courseNumber: 83, isSub: true },
    ],
  },
  {
    category: "IT and software",
    icon: "/CourseListFilter/chart-bar-horizontal.svg",
    subCategories: [
      { name: "networking", courseNumber: 340, isSub: true },
      { name: "security", courseNumber: 560, isSub: true },
      { name: "operating systems", courseNumber: 230, isSub: true },
      { name: "databases", courseNumber: 405, isSub: true },
      { name: "cloud computing", courseNumber: 612, isSub: true },
      { name: "devops", courseNumber: 198, isSub: true },
      { name: "support and operations", courseNumber: 174, isSub: true },
    ],
  },
  {
    category: "office productivity",
    icon: "/CourseListFilter/bug-droid.svg",
    subCategories: [
      { name: "microsoft office", courseNumber: 480, isSub: true },
      { name: "google workspace", courseNumber: 210, isSub: true },
      { name: "data entry", courseNumber: 97, isSub: true },
      { name: "presentations", courseNumber: 354, isSub: true },
      { name: "productivity tools", courseNumber: 142, isSub: true },
      { name: "time management", courseNumber: 221, isSub: true },
      { name: "communication tools", courseNumber: 183, isSub: true },
    ],
  },
  {
    category: "personal development",
    icon: "/CourseListFilter/receipt.svg",
    subCategories: [
      { name: "personal productivity", courseNumber: 370, isSub: true },
      { name: "leadership", courseNumber: 460, isSub: true },
      { name: "career development", courseNumber: 195, isSub: true },
      { name: "parenting", courseNumber: 88, isSub: true },
      { name: "creativity", courseNumber: 255, isSub: true },
      { name: "public speaking", courseNumber: 170, isSub: true },
      { name: "self esteem", courseNumber: 90, isSub: true },
    ],
  },
  {
    category: "design",
    icon: "/CourseListFilter/pen-nib.svg",
    subCategories: [
      { name: "graphic design", courseNumber: 590, isSub: true },
      { name: "web design", courseNumber: 450, isSub: true },
      { name: "design tools", courseNumber: 330, isSub: true },
      { name: "user experience", courseNumber: 290, isSub: true },
      { name: "game design", courseNumber: 345, isSub: true },
      { name: "3d modeling", courseNumber: 420, isSub: true },
      { name: "animation", courseNumber: 310, isSub: true },
    ],
  },
  {
    category: "marketing",
    icon: "/CourseListFilter/megaphone.svg",
    subCategories: [
      { name: "digital marketing", courseNumber: 710, isSub: true },
      { name: "social media marketing", courseNumber: 620, isSub: true },
      { name: "branding", courseNumber: 275, isSub: true },
      { name: "content marketing", courseNumber: 315, isSub: true },
      { name: "seo", courseNumber: 450, isSub: true },
      { name: "email marketing", courseNumber: 285, isSub: true },
      { name: "marketing strategy", courseNumber: 370, isSub: true },
    ],
  },
  {
    category: "lifestyle",
    icon: "/CourseListFilter/package.svg",
    subCategories: [
      { name: "arts and crafts", courseNumber: 260, isSub: true },
      { name: "travel", courseNumber: 195, isSub: true },
      { name: "gaming", courseNumber: 85, isSub: true },
      { name: "beauty and makeup", courseNumber: 120, isSub: true },
      { name: "home improvement", courseNumber: 310, isSub: true },
      { name: "pet care", courseNumber: 75, isSub: true },
      { name: "gardening", courseNumber: 160, isSub: true },
    ],
  },
  {
    category: "photography and video",
    icon: "/CourseListFilter/camera.svg",
    subCategories: [
      { name: "photography", courseNumber: 720, isSub: true },
      { name: "video design", courseNumber: 380, isSub: true },
      { name: "video production", courseNumber: 295, isSub: true },
      { name: "photo editing", courseNumber: 170, isSub: true },
      { name: "lighting", courseNumber: 210, isSub: true },
      { name: "digital photography", courseNumber: 335, isSub: true },
      { name: "video editing", courseNumber: 400, isSub: true },
    ],
  },
  {
    category: "music",
    icon: "/CourseListFilter/headset.svg",
    subCategories: [
      { name: "music theory", courseNumber: 520, isSub: true },
      { name: "instruments", courseNumber: 395, isSub: true },
      { name: "music production", courseNumber: 430, isSub: true },
      { name: "singing", courseNumber: 285, isSub: true },
      { name: "songwriting", courseNumber: 150, isSub: true },
      { name: "music composition", courseNumber: 320, isSub: true },
      { name: "djing", courseNumber: 110, isSub: true },
    ],
  },
  {
    category: "health and fitness",
    icon: "/CourseListFilter/first-aid-kit.svg",
    subCategories: [
      { name: "yoga", courseNumber: 345, isSub: true },
      { name: "nutrition", courseNumber: 240, isSub: true },
      { name: "mental health", courseNumber: 175, isSub: true },
      { name: "fitness", courseNumber: 510, isSub: true },
      { name: "meditation", courseNumber: 200, isSub: true },
      { name: "sports", courseNumber: 290, isSub: true },
      { name: "wellness", courseNumber: 265, isSub: true },
    ],
  },
];
