import { CourseData } from "@/types/courseFilter";

export const categories: CourseData[] = [
  {
    category: "development",
    icon: "/CourseListFilter/cpu.svg",
    subCategories: [
      { name: "web development", courseNumber: 574 },
      { name: "data science", courseNumber: 568 },
      { name: "mobile development", courseNumber: 1345 },
      { name: "software testing", courseNumber: 317 },
      { name: "software engineering", courseNumber: 31 },
      { name: "software development tools", courseNumber: 558 },
      { name: "no-code development", courseNumber: 37 },
    ],
  },
  {
    category: "business",
    icon: "/CourseListFilter/hand-shake.svg",
    subCategories: [
      { name: "entrepreneurship", courseNumber: 150 },
      { name: "business strategy", courseNumber: 432 },
      { name: "project management", courseNumber: 298 },
      { name: "business law", courseNumber: 89 },
      { name: "business analytics", courseNumber: 223 },
      { name: "sales", courseNumber: 314 },
      { name: "business communication", courseNumber: 187 },
    ],
  },
  {
    category: "finance and accounting",
    icon: "/CourseListFilter/credit-card.svg",
    subCategories: [
      { name: "financial analysis", courseNumber: 210 },
      { name: "accounting", courseNumber: 324 },
      { name: "investing", courseNumber: 489 },
      { name: "personal finance", courseNumber: 530 },
      { name: "taxes", courseNumber: 149 },
      { name: "financial modeling", courseNumber: 275 },
      { name: "cryptocurrency", courseNumber: 83 },
    ],
  },
  {
    category: "IT and software",
    icon: "/CourseListFilter/chart-bar-horizontal.svg",
    subCategories: [
      { name: "networking", courseNumber: 340 },
      { name: "security", courseNumber: 560 },
      { name: "operating systems", courseNumber: 230 },
      { name: "databases", courseNumber: 405 },
      { name: "cloud computing", courseNumber: 612 },
      { name: "devops", courseNumber: 198 },
      { name: "support and operations", courseNumber: 174 },
    ],
  },
  {
    category: "office productivity",
    icon: "/CourseListFilter/bug-droid.svg",
    subCategories: [
      { name: "microsoft office", courseNumber: 480 },
      { name: "google workspace", courseNumber: 210 },
      { name: "data entry", courseNumber: 97 },
      { name: "presentations", courseNumber: 354 },
      { name: "productivity tools", courseNumber: 142 },
      { name: "time management", courseNumber: 221 },
      { name: "communication tools", courseNumber: 183 },
    ],
  },
  {
    category: "personal development",
    icon: "/CourseListFilter/receipt.svg",
    subCategories: [
      { name: "personal productivity", courseNumber: 370 },
      { name: "leadership", courseNumber: 460 },
      { name: "career development", courseNumber: 195 },
      { name: "parenting", courseNumber: 88 },
      { name: "creativity", courseNumber: 255 },
      { name: "public speaking", courseNumber: 170 },
      { name: "self esteem", courseNumber: 90 },
    ],
  },
  {
    category: "design",
    icon: "/CourseListFilter/pen-nib.svg",
    subCategories: [
      { name: "graphic design", courseNumber: 590 },
      { name: "web design", courseNumber: 450 },
      { name: "design tools", courseNumber: 330 },
      { name: "user experience", courseNumber: 290 },
      { name: "game design", courseNumber: 345 },
      { name: "3d modeling", courseNumber: 420 },
      { name: "animation", courseNumber: 310 },
    ],
  },
  {
    category: "marketing",
    icon: "/CourseListFilter/megaphone.svg",
    subCategories: [
      { name: "digital marketing", courseNumber: 710 },
      { name: "social media marketing", courseNumber: 620 },
      { name: "branding", courseNumber: 275 },
      { name: "content marketing", courseNumber: 315 },
      { name: "seo", courseNumber: 450 },
      { name: "email marketing", courseNumber: 285 },
      { name: "marketing strategy", courseNumber: 370 },
    ],
  },
  {
    category: "lifestyle",
    icon: "/CourseListFilter/package.svg",
    subCategories: [
      { name: "arts and crafts", courseNumber: 260 },
      { name: "travel", courseNumber: 195 },
      { name: "gaming", courseNumber: 85 },
      { name: "beauty and makeup", courseNumber: 120 },
      { name: "home improvement", courseNumber: 310 },
      { name: "pet care", courseNumber: 75 },
      { name: "gardening", courseNumber: 160 },
    ],
  },
  {
    category: "photography and video",
    icon: "/CourseListFilter/camera.svg",
    subCategories: [
      { name: "photography", courseNumber: 720 },
      { name: "video design", courseNumber: 380 },
      { name: "video production", courseNumber: 295 },
      { name: "photo editing", courseNumber: 170 },
      { name: "lighting", courseNumber: 210 },
      { name: "digital photography", courseNumber: 335 },
      { name: "video editing", courseNumber: 400 },
    ],
  },
  {
    category: "music",
    icon: "/CourseListFilter/headset.svg",
    subCategories: [
      { name: "music theory", courseNumber: 520 },
      { name: "instruments", courseNumber: 395 },
      { name: "music production", courseNumber: 430 },
      { name: "singing", courseNumber: 285 },
      { name: "songwriting", courseNumber: 150 },
      { name: "music composition", courseNumber: 320 },
      { name: "djing", courseNumber: 110 },
    ],
  },
  {
    category: "health and fitness",
    icon: "/CourseListFilter/first-aid-kit.svg",
    subCategories: [
      { name: "yoga", courseNumber: 345 },
      { name: "nutrition", courseNumber: 240 },
      { name: "mental health", courseNumber: 175 },
      { name: "fitness", courseNumber: 510 },
      { name: "meditation", courseNumber: 200 },
      { name: "sports", courseNumber: 290 },
      { name: "wellness", courseNumber: 265 },
    ],
  },
];
