import { CourseFilterData } from "@/types/courseFilter";

export const categories: CourseFilterData[] = [
  {
    title: "category",
    children: [
      {
        title: "development",
        icon: "/CourseListFilter/cpu.svg",
        children: [
          { title: "web development", courseNumber: 574, isSub: true },
          { title: "data science", courseNumber: 568, isSub: true },
          { title: "mobile development", courseNumber: 1345, isSub: true },
          { title: "software testing", courseNumber: 317, isSub: true },
          { title: "software engineering", courseNumber: 31, isSub: true },
          { title: "software development tools", courseNumber: 558, isSub: true },
          { title: "no-code development", courseNumber: 37, isSub: true },
        ],
      },
      {
        title: "business",
        icon: "/CourseListFilter/hand-shake.svg",
        children: [
          { title: "entrepreneurship", courseNumber: 150, isSub: true },
          { title: "business strategy", courseNumber: 432, isSub: true },
          { title: "project management", courseNumber: 298, isSub: true },
          { title: "business law", courseNumber: 89, isSub: true },
          { title: "business analytics", courseNumber: 223, isSub: true },
          { title: "sales", courseNumber: 314, isSub: true },
          { title: "business communication", courseNumber: 187, isSub: true },
        ],
      },
      {
        title: "finance and accounting",
        icon: "/CourseListFilter/credit-card.svg",
        children: [
          { title: "financial analysis", courseNumber: 210, isSub: true },
          { title: "accounting", courseNumber: 324, isSub: true },
          { title: "investing", courseNumber: 489, isSub: true },
          { title: "personal finance", courseNumber: 530, isSub: true },
          { title: "taxes", courseNumber: 149, isSub: true },
          { title: "financial modeling", courseNumber: 275, isSub: true },
          { title: "cryptocurrency", courseNumber: 83, isSub: true },
        ],
      },
      {
        title: "IT and software",
        icon: "/CourseListFilter/chart-bar-horizontal.svg",
        children: [
          { title: "networking", courseNumber: 340, isSub: true },
          { title: "security", courseNumber: 560, isSub: true },
          { title: "operating systems", courseNumber: 230, isSub: true },
          { title: "databases", courseNumber: 405, isSub: true },
          { title: "cloud computing", courseNumber: 612, isSub: true },
          { title: "devops", courseNumber: 198, isSub: true },
          { title: "support and operations", courseNumber: 174, isSub: true },
        ],
      },
      {
        title: "office productivity",
        icon: "/CourseListFilter/bug-droid.svg",
        children: [
          { title: "microsoft office", courseNumber: 480, isSub: true },
          { title: "google workspace", courseNumber: 210, isSub: true },
          { title: "data entry", courseNumber: 97, isSub: true },
          { title: "presentations", courseNumber: 354, isSub: true },
          { title: "productivity tools", courseNumber: 142, isSub: true },
          { title: "time management", courseNumber: 221, isSub: true },
          { title: "communication tools", courseNumber: 183, isSub: true },
        ],
      },
      {
        title: "personal development",
        icon: "/CourseListFilter/receipt.svg",
        children: [
          { title: "personal productivity", courseNumber: 370, isSub: true },
          { title: "leadership", courseNumber: 460, isSub: true },
          { title: "career development", courseNumber: 195, isSub: true },
          { title: "parenting", courseNumber: 88, isSub: true },
          { title: "creativity", courseNumber: 255, isSub: true },
          { title: "public speaking", courseNumber: 170, isSub: true },
          { title: "self esteem", courseNumber: 90, isSub: true },
        ],
      },
      {
        title: "design",
        icon: "/CourseListFilter/pen-nib.svg",
        children: [
          { title: "graphic design", courseNumber: 590, isSub: true },
          { title: "web design", courseNumber: 450, isSub: true },
          { title: "design tools", courseNumber: 330, isSub: true },
          { title: "user experience", courseNumber: 290, isSub: true },
          { title: "game design", courseNumber: 345, isSub: true },
          { title: "3d modeling", courseNumber: 420, isSub: true },
          { title: "animation", courseNumber: 310, isSub: true },
        ],
      },
      {
        title: "marketing",
        icon: "/CourseListFilter/megaphone.svg",
        children: [
          { title: "digital marketing", courseNumber: 710, isSub: true },
          { title: "social media marketing", courseNumber: 620, isSub: true },
          { title: "branding", courseNumber: 275, isSub: true },
          { title: "content marketing", courseNumber: 315, isSub: true },
          { title: "seo", courseNumber: 450, isSub: true },
          { title: "email marketing", courseNumber: 285, isSub: true },
          { title: "marketing strategy", courseNumber: 370, isSub: true },
        ],
      },
      {
        title: "lifestyle",
        icon: "/CourseListFilter/package.svg",
        children: [
          { title: "arts and crafts", courseNumber: 260, isSub: true },
          { title: "travel", courseNumber: 195, isSub: true },
          { title: "gaming", courseNumber: 85, isSub: true },
          { title: "beauty and makeup", courseNumber: 120, isSub: true },
          { title: "home improvement", courseNumber: 310, isSub: true },
          { title: "pet care", courseNumber: 75, isSub: true },
          { title: "gardening", courseNumber: 160, isSub: true },
        ],
      },
      {
        title: "photography and video",
        icon: "/CourseListFilter/camera.svg",
        children: [
          { title: "photography", courseNumber: 720, isSub: true },
          { title: "video design", courseNumber: 380, isSub: true },
          { title: "video production", courseNumber: 295, isSub: true },
          { title: "photo editing", courseNumber: 170, isSub: true },
          { title: "lighting", courseNumber: 210, isSub: true },
          { title: "digital photography", courseNumber: 335, isSub: true },
          { title: "video editing", courseNumber: 400, isSub: true },
        ],
      },
      {
        title: "music",
        icon: "/CourseListFilter/headset.svg",
        children: [
          { title: "music theory", courseNumber: 520, isSub: true },
          { title: "instruments", courseNumber: 395, isSub: true },
          { title: "music production", courseNumber: 430, isSub: true },
          { title: "singing", courseNumber: 285, isSub: true },
          { title: "songwriting", courseNumber: 150, isSub: true },
          { title: "music composition", courseNumber: 320, isSub: true },
          { title: "djing", courseNumber: 110, isSub: true },
        ],
      },
      {
        title: "health and fitness",
        icon: "/CourseListFilter/first-aid-kit.svg",
        children: [
          { title: "yoga", courseNumber: 345, isSub: true },
          { title: "nutrition", courseNumber: 240, isSub: true },
          { title: "mental health", courseNumber: 175, isSub: true },
          { title: "fitness", courseNumber: 510, isSub: true },
          { title: "meditation", courseNumber: 200, isSub: true },
          { title: "sports", courseNumber: 290, isSub: true },
          { title: "wellness", courseNumber: 265, isSub: true },
        ],
      },
    ],
  },
  {
    title: "tools",
    children: [
      { title: "html5", courseNumber: 94, isSub: true },
      { title: "css 3", courseNumber: 61, isSub: true },
    ],
  },
];
